name: Tests
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Show Python & pip info
        run: |
          python --version
          python -m pip --version
          python -m pip list

      - name: Install build tools and dependencies (with retry)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          n=0
          until [ "$n" -ge 3 ]
          do
            python -m pip install -r requirements.txt && break
            n=$((n+1))
            echo "pip install failed, retry #$n"
            sleep 5
          done

      - name: Run pytest
        run: |
          pytest -v tests/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            .pytest_cache
            .coverage
            htmlcov/

