name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Upgrade pip/tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies (retry)
        run: |
          retries=0
          until [ $retries -ge 3 ]
          do
            python -m pip install -r requirements.txt && break
            retries=$((retries+1))
            echo "Retrying pip install ($retries)"
            sleep 5
          done

      - name: Show workspace
        run: |
          pwd
          ls -la
          echo "PYTHONPATH=$PYTHONPATH"

      - name: Show env and python info
        run: |
          python --version
          python -V
          python -c "import sys, json; print(json.dumps({'sys_path': sys.path}, default=str))"
          python -m pip --version
          python -m pip list

      - name: Run pytest (capture output)
        run: |
          mkdir -p action_artifacts
          python -m pytest -vv tests/ 2>&1 | tee action_artifacts/pytest.log || true
          python -c "import sys, json; print(json.dumps({'rc': sys.exit if False else 0}))" || true
        shell: bash

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            .pytest_cache
            action_artifacts/pytest.log

