name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Upgrade pip/tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies (retry)
        run: |
          retries=0
          until [ $retries -ge 3 ]
          do
            python -m pip install -r requirements.txt && break
            retries=$((retries+1))
            echo "Retrying pip install ($retries)"
            sleep 5
          done

      - name: Run tests
        run: pytest -q tests/

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: .pytest_cache

